[server]
headless = true
port = 8501
address = 0.0.0.0
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
serverAddress = "167.71.235.91"

[logger]
level = "error"

[client]
showErrorDetails = true
